package com.example.gsong.models;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

/**
 * Represents a Song entity for the Room database
 * Implements Serializable so it can be saved in a Bundle
 */
@Entity
public class Song implements Serializable {

    //Primary key ID autogenerated by Room
    @PrimaryKey(autoGenerate = true)
    public int id;

    //The title of the song
    public String title;

    //The filename of the song
    public String fileName;

    //The language of the song
    public String language;

    /**
     * Default constructor (required by Room).
     */
    public Song() {}

    /**
     * Constructor to create a Song with a title and fileName
     * @param title = the title of the song
     * @param fileName = the file name
     */
    public Song(String title, String fileName) {
        this.title = title;
        this.fileName = fileName;
    }

}


